### PR TITLE
Spectrogram

### PR DESCRIPTION
**Pull request by zz85**
Attempt to make spectrogram. Somehow doesn't seem near as good as http://www.warmplace.ru/soft/phonopaper/

I'm guessing that there's a couple of reasons
1. FFT window isn't large enough
2. We are losing resolution in the lower spectrum of FFT
3. I'm completely missing a better or more efficient algorithm at doing this.

For now I might attempt to do a naive form of denoising for which I would either
1) convert linear scale to log scale, then denoise
2) denoise in linear scale, then convert to log scale

Anyone with better ideas?

@notthetup

### CODE REVIEW

**Comment by zz85** [comment]
image

**Comment by notthetup** [comment]
Sorry.. Super busy this week. Will try to take a look sometime next week.

**Comment by zz85** [comment]
Ok I'll be merging this for now. This PR also includes camera selecting option for User Media cc @honnet 

Personally I think there's some limitations with this approach. Thanks to Martin @mdda for suggesting a different approach to doing this spectrum analyzer https://code.mythtv.org/trac/changeset/845b087f99b5daf76de3c0381f88e2265ca858a3/mythtv

I think we should try out the Goertzel algorithm in a separate PR or explore other alternatives :)

**Comment by notthetup** [comment]
Well what do you know? https://github.com/notthetup/goertzel-filter

**Comment by mdda** [comment]
@notthetup great find!

One thing, though, is that rather than ~96 individual filters, it's much more efficient to run each time-step over an array of filter-updates (i.e. implement the filter operations as vector ones).  Not only does this lower the overhead of having lots of filter objects, but also the memory layout makes it much more cache-friendly.

**Pull request merged**
